---
version: 2

references:
  environments:
    mysql: &mysqlEnvironment
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: "statesman_test"
    postgres: &postgresEnvironment
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "statesman_test"
  steps: &steps
    - checkout

    - type: shell
      name: Write RAILS_VERSION to a file so we can use it for caching purposes
      command: echo "$RAILS_VERSION" > ~/RAILS_VERSION.txt

    - type: cache-restore
      key: statesman-{{ checksum "Gemfile" }}-{{ checksum "~/RAILS_VERSION.txt" }}

    - run: gem install bundler -v 2.0.1
    - run: bundle install --path vendor/bundle

    - type: cache-save
      key: statesman-{{ checksum "Gemfile" }}-{{ checksum "~/RAILS_VERSION.txt" }}
      paths:
        - vendor/bundle

    - run: bundle exec rubocop

    - run: dockerize -wait tcp://localhost:$DATABASE_DEPENDENCY_PORT -timeout 1m

    - run: bundle exec rake

    - type: store_test_results
      path: /tmp/test-results

jobs:
  ################################################################################
  # Ruby 2.4.7
  ################################################################################
  build-ruby247-rails-523-mysql:
    docker:
      - image: circleci/ruby:2.4.7
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=5.2.3
          - DATABASE_URL=mysql2://root@127.0.0.1/statesman_test
          - DATABASE_DEPENDENCY_PORT=3306
      - image: circleci/mysql:5.7.18
        environment: *mysqlEnvironment
    steps: *steps
  build-ruby247-rails-523-postgres:
    docker:
      - image: circleci/ruby:2.4.7
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=5.2.3
          - DATABASE_URL=postgres://postgres@localhost/statesman_test
          - DATABASE_DEPENDENCY_PORT=5432
      - image: circleci/postgres:9.6
        environment: *postgresEnvironment
    steps: *steps
  build-ruby247-rails-600-mysql:
    docker:
      - image: circleci/ruby:2.4.7
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=6.0.0
          - DATABASE_URL=mysql2://root@127.0.0.1/statesman_test
          - DATABASE_DEPENDENCY_PORT=3306
      - image: circleci/mysql:5.7.18
        environment: *mysqlEnvironment
    steps: *steps
  build-ruby247-rails-600-postgres:
    docker:
      - image: circleci/ruby:2.4.7
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=6.0.0
          - DATABASE_URL=postgres://postgres@localhost/statesman_test
          - DATABASE_DEPENDENCY_PORT=5432
      - image: circleci/postgres:9.6
        environment: *postgresEnvironment
    steps: *steps

  ################################################################################
  # Ruby 2.5.6
  ################################################################################
  build-ruby256-rails-523-mysql:
    docker:
      - image: circleci/ruby:2.5.6
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=5.2.3
          - DATABASE_URL=mysql2://root@127.0.0.1/statesman_test
          - DATABASE_DEPENDENCY_PORT=3306
      - image: circleci/mysql:5.7.18
        environment: *mysqlEnvironment
    steps: *steps
  build-ruby256-rails-523-postgres:
    docker:
      - image: circleci/ruby:2.5.6
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=5.2.3
          - DATABASE_URL=postgres://postgres@localhost/statesman_test
          - DATABASE_DEPENDENCY_PORT=5432
      - image: circleci/postgres:9.6
        environment: *postgresEnvironment
    steps: *steps
  build-ruby256-rails-600-mysql:
    docker:
      - image: circleci/ruby:2.5.6
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=6.0.0
          - DATABASE_URL=mysql2://root@127.0.0.1/statesman_test
          - DATABASE_DEPENDENCY_PORT=3306
      - image: circleci/mysql:5.7.18
        environment: *mysqlEnvironment
    steps: *steps
  build-ruby256-rails-600-postgres:
    docker:
      - image: circleci/ruby:2.5.6
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=6.0.0
          - DATABASE_URL=postgres://postgres@localhost/statesman_test
          - DATABASE_DEPENDENCY_PORT=5432
      - image: circleci/postgres:9.6
        environment: *postgresEnvironment
    steps: *steps

  ################################################################################
  # Ruby 2.6.2
  ################################################################################
  build-ruby263-rails-523-mysql:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=5.2.3
          - DATABASE_URL=mysql2://root@127.0.0.1/statesman_test
          - DATABASE_DEPENDENCY_PORT=3306
      - image: circleci/mysql:5.7.18
        environment: *mysqlEnvironment
    steps: *steps
  build-ruby263-rails-523-postgres:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=5.2.3
          - DATABASE_URL=postgres://postgres@localhost/statesman_test
          - DATABASE_DEPENDENCY_PORT=5432
      - image: circleci/postgres:9.6
        environment: *postgresEnvironment
    steps: *steps
  build-ruby263-rails-600-mysql:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=6.0.0
          - DATABASE_URL=mysql2://root@127.0.0.1/statesman_test
          - DATABASE_DEPENDENCY_PORT=3306
      - image: circleci/mysql:5.7.18
        environment: *mysqlEnvironment
    steps: *steps
  build-ruby263-rails-600-postgres:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=6.0.0
          - DATABASE_URL=postgres://postgres@localhost/statesman_test
          - DATABASE_DEPENDENCY_PORT=5432
      - image: circleci/postgres:9.6
        environment: *postgresEnvironment
    steps: *steps

  ################################################################################
  # Ruby 2.6.2, Rails latest
  ################################################################################
  build-ruby262-rails-master-mysql:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=master
          - DATABASE_URL=mysql2://root@127.0.0.1/statesman_test
          - DATABASE_DEPENDENCY_PORT=3306
      - image: circleci/mysql:5.7.18
        environment: *mysqlEnvironment
    steps: *steps
  build-ruby262-rails-master-postgres:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          - BUNDLER_VERSION=2.0.1
          - RAILS_VERSION=master
          - DATABASE_URL=postgres://postgres@localhost/statesman_test
          - DATABASE_DEPENDENCY_PORT=5432
      - image: circleci/postgres:9.6
        environment: *postgresEnvironment
    steps: *steps

workflows:
  version: 2
  tests:
    jobs:
      - build-ruby247-rails-523-mysql
      - build-ruby247-rails-523-postgres
      - build-ruby247-rails-600-mysql
      - build-ruby247-rails-600-postgres
      - build-ruby256-rails-523-mysql
      - build-ruby256-rails-523-postgres
      - build-ruby256-rails-600-mysql
      - build-ruby256-rails-600-postgres
      - build-ruby263-rails-523-mysql
      - build-ruby263-rails-523-postgres
      - build-ruby263-rails-600-mysql
      - build-ruby263-rails-600-postgres
      - build-ruby262-rails-master-mysql
      - build-ruby262-rails-master-postgres
